name: CI/CD

on:
  push:
    branches: [main, move-to-service]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: timescale/timescaledb:latest-pg16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sync_airbnb_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Run ruff linter
        run: ruff check .

      - name: Run black formatter check
        run: black --check .

      - name: Run mypy type checker
        run: mypy sync_airbnb/
        continue-on-error: true  # Don't fail CI on mypy errors yet

      - name: Set up test database
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/sync_airbnb_test
          MODE: admin  # Set to admin mode to avoid requiring ACCOUNT_ID
        run: |
          # Run migrations
          alembic upgrade head

      - name: Run tests with coverage
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/sync_airbnb_test
          MODE: admin  # Set to admin mode to avoid requiring ACCOUNT_ID
          # Dummy credentials for tests (not actually used, but required by config.py)
          AIRBNB_COOKIE: "test_cookie"
          AIRBNB_API_KEY: "test_api_key"
          X_CLIENT_VERSION: "test_version"
          X_AIRBNB_CLIENT_TRACE_ID: "test_trace_id"
          USER_AGENT: "test_user_agent"
        run: |
          # Clean pycache to avoid pytest import conflicts with duplicate test filenames
          find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
          pytest --cov=sync_airbnb --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  docker-test:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create test .env file
        run: |
          cat > .env << EOF
          DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
          LOG_LEVEL=INFO
          MODE=admin
          AIRBNB_COOKIE=test_cookie
          AIRBNB_API_KEY=test_api_key
          X_CLIENT_VERSION=test_version
          X_AIRBNB_CLIENT_TRACE_ID=test_trace_id
          USER_AGENT=test_user_agent
          EOF

      - name: Build Docker image
        run: docker-compose build

      - name: Start services
        run: docker-compose up -d

      - name: Wait for application to be ready
        run: |
          echo "Waiting for application to start..."
          timeout 60 bash -c 'until curl -f http://localhost:8000/health; do sleep 2; done' || {
            echo "Application failed to start. Container logs:"
            docker-compose logs app
            exit 1
          }

      - name: Test health endpoint
        run: |
          response=$(curl -s http://localhost:8000/health)
          echo "Health response: $response"
          echo "$response" | grep -q '"status":"ok"' || {
            echo "Health check failed"
            docker-compose logs app
            exit 1
          }

      - name: Test ready endpoint
        run: |
          response=$(curl -s http://localhost:8000/health/ready)
          echo "Ready response: $response"
          echo "$response" | grep -q '"status":"ready"' || {
            echo "Ready check failed"
            docker-compose logs app
            exit 1
          }

      - name: Check for startup errors in logs
        run: |
          logs=$(docker-compose logs app)
          if echo "$logs" | grep -iE "error|exception|traceback" | grep -v "continue-on-error"; then
            echo "Found errors in application logs:"
            echo "$logs"
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: docker-compose down -v

  build:
    runs-on: ubuntu-latest
    needs: [test, docker-test]
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=main-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
